language: java

matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode9.3
      jdk: oraclejdk8

notifications:
  email: false
