language: java

matrix:
  include:
    - os: linux
      jdk: openjdk11
    - os: linux
      jdk: oraclejdk11
    - os: osx
      osx_image: xcode10.1
      jdk: oraclejdk11
    - os: osx
      osx_image: xcode10.2
      jdk: oraclejdk12

notifications:
  email: false
