package it.polimi.ingsw.model.weapons;

public enum WeaponType {
    CYBERBLADE,
    ELECTROSCYTHE,
    FLAMETHROWER,
    FURNACE,
    GRENADELAUNCHER,
    HEATSEEKER,
    HELLION,
    LOCKRIFLE,
    MACHINEGUN,
    PLASMAGUN,
    POWERGLOVE,
    RAILGUN,
    ROCKETLAUNCHER,
    SHOCKWAVE,
    SHOTGUN,
    SLEDGEHAMMER,
    THOR,
    TRACTORBEAM,
    VORTEXCANNON,
    WHISPER,
    ZX2
}
