package it.polimi.ingsw.common.dialogs;

public enum Dialog {
    SPAWN,
    MOVE,
    WEAPON_GRAB,
    PAY_COST_POWERUP,
    WEAPON_SHOOT,
    WEAPON_ATTACK,
    RELOAD,
    DISCARD_WEAPON,
    DISCARD_POWERUP,
    SHOOT_TARGET,
    SELECT_POWERUP,
    ACTION_SELECT,
    TARGET_PLAYER,
    BONUS_MOVEMENT,
    TARGET_SQUARE,
    SKIP,
    USER_CONNECTED,
    INVALID_SELECTION,
    NEW_SELECTION,
    INVALID_INTEGER,
    CONFIRM,
    FINAL_STANDINGS
}
