package it.polimi.ingsw.controller;

public enum SelectDialog {
    SPAWN_DIALOG,
    SELECT_MOVE_DIALOG,
    MOVE_DIALOG,
    WEAPON_GRAB_DIALOG,
    PAY_COST_POWERUP_DIALOG,
    WEAPON_SHOOT_DIALOG,
    WEAPON_ATTACK_DIALOG,
    RELOAD_DIALOG,
    DISCARD_WEAPON_DIALOG,
    DISCARD_POWERUP_DIALOG,
    SHOOT_TARGET_DIALOG,
    SELECT_POWERUP_DIALOG,
    ACTION_SELECT_DIALOG,
    TARGET_PLAYER_DIALOG,
    BONUS_MOV_DIALOG,
    TARGET_SQUARE_DIALOG
}
